(evil-leader/set-key "gP" 'magit-key-mode-popup-pushing)
(evil-leader/set-key "gc" 'magit-key-mode-popup-committing)
(evil-leader/set-key "gl" 'magit-key-mode-popup-logging)
(evil-leader/set-key "gr" 'magit-reflog)
(evil-leader/set-key "gD" 'magit-diff-working-tree)
(evil-leader/set-key "gB" 'magit-blame-mode)
(evil-leader/set-key "gb" 'magit-key-mode-popup-branching)
(evil-leader/set-key "gn" 'git-gutter:next-hunk)
(evil-leader/set-key "gp" 'git-gutter:previous-hunk)
(evil-leader/set-key "gh" 'git-gutter:popup-hunk)
(evil-leader/set-key "gx" 'git-gutter:revert-hunk)
(evil-leader/set-key "ga" 'git-gutter:stage-hunk)

(evil-set-initial-state 'git-commit-mode 'insert)
