(define-key org-mode-map (kbd "C-c C-.") 'org-time-stamp-inactive)
(define-key org-mode-map (kbd "M-p")     'org-metaup)
(define-key org-mode-map (kbd "M-n")     'org-metadown)
(define-key org-mode-map (kbd "C-c c")   'org-columns)
(define-key org-mode-map (kbd "C-c C-k") 'org/ctrl-c-ctrl-k)
(define-key org-mode-map (kbd "C-c RET") 'org/ctrl-c-ret)
(define-key org-mode-map (kbd "C-c ;")   nil)

(bind-key* "<f12>" 'org-work-toggle-at-work)

(evil-global-set-key 'normal (kbd "SPC o a") 'org/agenda-dwim)
(evil-global-set-key 'normal (kbd "SPC o c") 'org-clock-goto)
(evil-global-set-key 'normal (kbd "SPC o d") 'org/goto-diary)
(evil-global-set-key 'normal (kbd "SPC o k") 'org-capture)
(evil-global-set-key 'normal (kbd "SPC o s") 'org-search-view)
(evil-global-set-key 'normal (kbd "SPC o n") 'org/goto-notes)
(evil-global-set-key 'normal (kbd "SPC o w") 'org/goto-work)
(evil-global-set-key 'normal (kbd "SPC o t") 'org/todo-list)
(evil-global-set-key 'normal (kbd "SPC o v") 'org/tags-list)

(define-key org-agenda-mode-map (kbd "C-f") 'evil-scroll-page-down)
(define-key org-agenda-mode-map (kbd "C-b") 'evil-scroll-page-up)
