(after 'haskell-mode
  (evil-define-key 'normal haskell-mode-map (kbd "SPC i i") 'haskell/insert-import)
  (evil-define-key 'normal haskell-mode-map (kbd "SPC i q") 'haskell/insert-qualified-import)
  (evil-define-key 'normal haskell-mode-map (kbd "SPC i l") 'haskell/insert-language-pragma)
  (evil-define-key 'normal haskell-mode-map (kbd "SPC i o") 'haskell/insert-ghc-option)

  (define-key haskell-mode-map (kbd "M-.")           'haskell-mode-tag-find)
  (define-key haskell-mode-map (kbd "M-,")           'pop-tag-mark)
  (define-key haskell-mode-map (kbd "M-P")           'flymake-goto-prev-error)
  (define-key haskell-mode-map (kbd "M-N")           'flymake-goto-next-error)
  (define-key haskell-mode-map (kbd "C-,")           'haskell-move-nested-left)
  (define-key haskell-mode-map (kbd "C-.")           'haskell-move-nested-right)
  (define-key haskell-mode-map (kbd "C-c c")         'haskell-process-cabal)
  (define-key haskell-mode-map (kbd "C-c C-c")       'haskell-process-cabal-build)
  (define-key haskell-mode-map (kbd "C-c C-d")       'haskell-w3m-open-haddock)
  (define-key haskell-mode-map (kbd "C-c C-l")       'haskell-process-load-file)
  (define-key haskell-mode-map (kbd "C-c C-f")       'haskell-cabal-visit-file)
  (define-key haskell-mode-map (kbd "C-c C-h")       'haskell-hoogle)
  (define-key haskell-mode-map (kbd "C-c C-t")       'haskell-process-do-type)
  (define-key haskell-mode-map (kbd "C-c C-i")       'haskell-process-do-info)
  (define-key haskell-mode-map (kbd "C-c C-c")       'haskell-process-cabal-build)
  (define-key haskell-mode-map (kbd "C-c C-k")       'haskell-interactive-mode-clear)
  (define-key haskell-mode-map (kbd "M-q")           'haskell/format-dwim)
  (define-key haskell-mode-map (kbd "M-RET")         'haskell/meta-ret)
  (define-key haskell-mode-map (kbd "DEL")           'haskell/del)
  (define-key haskell-mode-map (kbd "C-c C-z")       'haskell-interactive-switch)
  )

(after 'haskell-cabal-mode
  (define-key haskell-cabal-mode-map (kbd "C-`")     'haskell-interactive-bring)
  (define-key haskell-cabal-mode-map (kbd "C-c C-k") 'haskell-interactive-mode-clear)
  (define-key haskell-cabal-mode-map (kbd "C-c C-c") 'haskell-process-cabal-build)
  (define-key haskell-cabal-mode-map (kbd "C-c c")   'haskell-process-cabal)
  )

(after 'haskell-interactive-mode
  (define-key haskell-interactive-mode-map (kbd "C-c C-h") 'haskell-hoogle)
  )

(after 'shm
  (define-key shm-map (kbd "C-k")        'shm/kill-node)
  (define-key shm-map (kbd "C-c C-s")    'shm/case-split)
  (define-key shm-map (kbd "C-<return>") 'shm/newline-indent)

  ;; undefine commands that interfere with smart ops, etc.
  (define-key shm-map (kbd "RET") nil)
  (define-key shm-map (kbd ",") nil)
  (define-key shm-map (kbd ":") nil)
  (define-key shm-map (kbd "#") nil)
  (define-key shm-map (kbd "-") nil)
  (define-key shm-map (kbd "DEL") nil)
  (define-key shm-map (kbd "C-<backspace>") nil)
  (define-key shm-map (kbd "<backtab>") nil)
  (define-key shm-map (kbd "TAB") nil)
  (define-key shm-map (kbd "M-r") nil)
  )
