(require 'iedit)

(bind-key "M-r" 'iedit-mode)

(bind-key "M-r c" 'iedit-toggle-case-sensitive iedit-mode-keymap)
(bind-key "M-r d" 'iedit-done iedit-mode-keymap)
(bind-key "M-r f" 'iedit-restrict-function iedit-mode-keymap)
(bind-key "M-r g" 'iedit-goto-first-occurrence iedit-mode-keymap)
(bind-key "M-r G" 'iedit-goto-last-occurrence iedit-mode-keymap)
(bind-key "M-r k" 'iedit-delete-occurrences iedit-mode-keymap)
(bind-key "M-r l" 'iedit-restrict-current-line iedit-mode-keymap)
(bind-key "M-r n" 'iedit-next-occurrence iedit-mode-keymap)
(bind-key "M-r p" 'iedit-prev-occurrence iedit-mode-keymap)
(bind-key "M-r r" 'iedit/replace-read iedit-mode-keymap)
(bind-key "M-r R" 'iedit/restrict-to-region iedit-mode-keymap)
(bind-key "M-r t" 'iedit-toggle-selection iedit-mode-keymap)
(bind-key "M-r w" 'iedit/restrict-to-window iedit-mode-keymap)
(bind-key "M-r x" 'iedit/remove-region iedit-mode-keymap)
