(define-key emacs-lisp-mode-map (kbd "M-.") 'elisp-slime-nav-find-elisp-thing-at-point)
(define-key emacs-lisp-mode-map (kbd "C-c C-t") 'ert)
(define-key emacs-lisp-mode-map (kbd "C-c C-z") 'switch-to-ielm)
(define-key emacs-lisp-mode-map (kbd "C-c C-e") 'send-to-ielm)
(define-key emacs-lisp-mode-map (kbd "C-c RET") 'eval-in-ielm)
(define-key emacs-lisp-mode-map (kbd "M-RET")   'elisp/M-RET)
(define-key emacs-lisp-mode-map (kbd "C-c C-f") 'eval-buffer)
(define-key emacs-lisp-mode-map (kbd "C-c C-b") 'eval-buffer)
(define-key emacs-lisp-mode-map (kbd "C-c C-c") 'elisp/eval-dwim)
